{% set name = "asf_tools" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5c89123c4a6cf65c383502a02856f71be8a09a4e8593e2a9ad0f26a28ea9661f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - make_composite = asf_tools.composite:main
    - water_map = asf_tools.water_map:main
    - calculate_hand = asf_tools.hand.calculate:main

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=42
    - setuptools_scm >=3.4
    - wheel
  run:
    - python >=3.8
    - astropy
    - fiona
    - gdal >=3.3
    - numpy
    - pysheds
    - rasterio
    - scikit-fuzzy
    - scikit-image
    - shapely

test:
  imports:
    - asf_tools
    - asf_tools.composite
    - asf_tools.dem
    - asf_tools.hand
    - asf_tools.raster
    - asf_tools.threshold
    - asf_tools.tile
    - asf_tools.util
    - asf_tools.vector
    - asf_tools.water_map
  commands:
    - make_composite --help
    - water_map --help
    - calculate_hand --help

about:
  home: https://github.com/ASFHyP3/asf-tools
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Tools developed by ASF for working with SAR data

extra:
  recipe-maintainers:
    - jhkennedy
    - asjohnston-asf
    - jlrine2
